### PR TITLE
Submission Programming Assignment 7 (Marjolein and Sarah)

### PR DESCRIPTION
**Pull request by MarjoleinSpijkerman**

### CODE REVIEW

**Comment by IlseBarf** [comment]
README comments:
- You call a module ktinker twice, but it is called tkinter
- Try to specify what you are talking about, ("in the folder" -> "in the folder <name>")
- There are some spelling, phrasing, and interpunction errors:
     - "The main importance"
     - "All the need packages"
     - and some more
- We installed everything, following the instructions, but then there was no instructions on how to actually start the sudoku solver
- It was not clear from the README what the program actually does. We did not know that we had to design our own sudoku, which would then be solved by the solver
- A little bit more info about or at least the source of the original repo would be nice

**Comment by IlseBarf** [comment]
Sudoku comments:
- The sudoku won't fit on our screen, so we are missing the last one and a half lines
- Everything we say is a two. We did try it in a slightly noisy environment, but results like that should probably be added to the README
- Trying to solve an impossible sudoku will cause the program to crash. It is mentioned that it won't give a solution, but this is a bigger bug than that suggests. (in your code, you check if a box is already filled in, maybe also check for clashes within this if statement)
- Indentations don't properly show up in the information text, maybe there is a way to left-align the text

**Comment by MarjoleinSpijkerman** [comment]
@IlseBarf 
Thank you very much for your helpful comments. We tried our best to implement your feedback as good as possible. 
We completely updated our README adding:
- information about the original repository
- our initial plan
- the changes that we made that lead to our final version of the code
- a complete description of the functionality of the code
Furthermore, we tried to clear up any confusion and removed the spelling/wording mistakes 


For the code part we added
- a check to see whether the inserted sudoku is valid before trying to solve it. Avoiding future errors
- Left aligned the text in the information section
- Made the interface scalable based on the size of the screen of the computer
- Improved the stability of the confusion matrix, by adding an error message when you want to run the statistics before there is any data. And by making sure that the number of saved predicted numbers is the same as the number of true values. 
- Improved the stability of the "manual override" button, by adding an error message when you try to insert a value that is not an integer digit between 1 and 9

Hopefully this solves all the problems you were having with our code!
Have a good evening!

**Comment by MarjoleinSpijkerman** [comment]
@IlseBarf @phat-vtcf 
Again thank you very much for your feedback. 
It was really clear, and it helped us find a bug that we did not know existed (the scalability of the interface). 
Furthermore, most of the suggestions you did for improving the code were possible to implement in a short timeframe, making them really helpful for the quality control. The only thing that was not possible to improve was the performance of the recognizer, but we added some extra explanations on that in the README. So, overall very good comments. 

To grade your help we decided on the following:
- How fair they have been in their requests and demands --> very fair demands, yet it is not possible to make improvements on the recognizer in less than a week. 9.5/10
- How clear and reproducible they have been in asking for clarification and reporting errors --> mostly clear, however the part on the spelling/wording mistakes could have been a bit clearer by giving both the incorrect version and maybe a suggestion on what to change it to. 9/10
- How helpful they have been in helping you improve the quality of your code/repo --> They made us aware of a bug that we did not know existed. 10/10

Total 28.5/30 = 9.5

**Comment by IlseBarf** [comment]
It's merged @phat-vtcf

**Pull request merged**
